### ISSUE TITLE
Getting array

### ISSUE THREAD

**Issue by arietto** [mashiro/rabbit#16]
Hello! Sorry for newbie question. Here is a code snippet: 

    void some_func(const rabbit::object& obj)
    {    
     const auto& children_elem = obj["children"];
     rabbit:array children = children_elem;//1
    //...
    }
The line with tag 1 fails. Why does it happen?
I'd like to check whether obj["children"] `is_array()` before assigning to rabbit:array.
I don't want to copy-paste raw string literals (minimize their usage).

**Comment by csteifel** [comment]
Can you give more details about the exact error you are getting? Since we don't know what the json structure is of obj its going to be hard to tell you what is going wrong without knowing what the error you are getting is. Is obj["children"] already populated? Is it a field you are attempting to create?

**Comment by arietto** [comment]
I have verbose compilation error. I need to produce deserialization. obj["children"] is already populated.
When I remove `const` from `some_func` (`void some_func(rabbit::object& obj)`), then compilation is OK.
I just need to have an example of typical `deserialize()` method signature which can accept `rabbit::document` or `rabbit::object`.
for example, `void deserialize(rabbit::value_ref& _json, My_pod* _pod);`

**Comment by csteifel** [comment]
so if you are looking to pass things as const I'd actually recommend using things listed here: https://github.com/mashiro/rabbit/blob/master/rabbit.hpp#L1444 such as `rabbit::const_object` or `rabbit::const_value_ref` etc. Without knowing what the exact compilation message is though I can't be sure exactly what your specific issue is.

**Comment by arietto** [comment]
Thank you! The problem has been solved after switching to `rabbit::const_` prefixed types.
