### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by MarcoG3** [mashiro/rabbit#2]
I can't find a way to create an array of objects.

```
rabbit::array myArray;
rabbit::object firstObj;
rabbit::object secondObj;

firstObj["name"] = "first";
firstObj["something"] = "something1";

myArray.push_back(firstObj);

secondObj["name"] = "second";
secondObj["something"] = "something2";

myArray.push_back(secondObj);
```

Looks like push_back function calls ```PushBack(T value, Allocator& allocator)``` and value must be a ```GenericValue``` since its then passed to its constructor. Any tip?

EDIT: looks like I can't pass rabbit::object to ```GenericValue``` constructor, there is no constructor that permits that.

**Comment by mashiro** [comment]
Oh, it's test leak.
I fixed this issue on mater, please try it.
https://github.com/mashiro/rabbit/commit/6922002317156b720eb5a129c94baaadde719d87

**Comment by MarcoG3** [comment]
It works now but I guess I have found another issue.

```
rabbit::array myarray;
rabbit::object obj1;

obj1[L"bla"] = L"abc";
obj1[L"bla2"] = L"abc2";

myarray.push_back(obj1);
myarray.push_back(obj1);

std::wstring strRes = myarray.str();
```

strRes = ```[{"bla":"abc","bla2":"abc2"},null]```

This does not happen if I push another object ```obj2 != obj1```. Thank you!
