### ISSUE TITLE
rabbit::object deep copy

### ISSUE THREAD

**Issue by MarcoG3** [mashiro/rabbit#3]
Is it possible to deep copy ```rabbit::object```? Rapidjson has a method ```CopyFrom``` that allows to do that. Currently, doing this does not result in a deep copy.

```
rabbit::object obj1;
obj1["param1"] = "value1";

rabbit::object obj2(obj1);
```

It looks like, from my tests, that when ```obj2``` goes out of scope, ```obj1``` is also affected. Another example:

```
rabbit::object obj1;
obj1["param1"] = "value1";

rabbit::object* heapObj = new rabbit::object(obj1);
```

Here, when ```obj1``` goes out of scope, ```heapObj``` is affected too, even if its allocated on heap.

Thanks!

**Comment by mashiro** [comment]
No, rabbit::value_ref (base of rabbit::object) is a wrapper object of GenericValue.
It behaves like a scoped_ptr.

**Comment by MarcoG3** [comment]
How can I make it last longer? The idea was to make a copy, I need it to live longer than scope its defined in.

**Comment by mashiro** [comment]
Your idea is maybe correct. but, ths library's concept is legacy platform support and no boost library.
Implementation cost of shared_ptr is very high.
If you can use shared_ptr on your environment, it is easy to wrap the rabbit::object in shared_ptr.

**Comment by MarcoG3** [comment]
I've wrapper ```rabbit::object``` in ```shared_ptr``` but it still behaves in the same way.
That's what gets called, in order, when I assign ```obj2 = obj1;```

1)
```
template <typename OtherTraits>
basic_object(const basic_value_ref<OtherTraits>& other)
	: base_type(other)
{}
```

2)
```
template <typename OtherTraits>
basic_value(const basic_value_ref<OtherTraits>& other)
	: member_type()
	, base_type(other)
{
	if (base_type::is_null())
		traits::set(*this, default_tag());
}
```

3)
```
explicit basic_value_base(native_value_type* value = 0, allocator_type* alloc = 0)
	: value_impl_(value)
	, alloc_impl_(alloc)
{}
```

In the last call (3), ```value_imp_``` and ```alloc_imp_``` are set ```NULL```. I've changed their types from ```scoped_ptr``` to ```std::shared_ptr``` but it behaves the same way. Could you give me a tip on how to continue?

**Comment by mashiro** [comment]
Sorry, explanation is not enough.
Currently, rabbit can not make a deep copy. That's because doing the swap inside assign operator.
Rather than change the internal, to warp the rabbit::object

e.g.
```cpp
std::shared_ptr<rabbit::object> make_object() {
  auto obj = std::make_shared<rabbit::object>();
  ...
  return obj;
}

int main() {
  auto obj = make_object();
  ...
}
```

**Comment by MarcoG3** [comment]
Thank you, I understand how I can create a `rabbit::object` from scratch but I need to get it from existing `rabbit::object` (I need to make a copy that lives longer on the heap).
With your example, even if I do `obj = scopedObj` the results will be exactly the same. Any tips? Thanks!

**Comment by mashiro** [comment]
I remembered, rabbit's memory are managed by root object. Allocator is shared in the same tree.
Node is all reference and it life time are same of root.
```cpp
rabbit::document doc ; // root
rabbit::object obj; // root
rabibt::object user = doc["user"]; // not root
```

**Comment by MarcoG3** [comment]
Thank you, a possible solution would be wrapping root document/object around a shared pointer.
