### ISSUE TITLE
Get float value in string not precisely 

### ISSUE THREAD

**Issue by sandfresh** [mashiro/rabbit#5]
For exmaple json like this {"player_credit",49805.82}
If I get credit in string, rabbit will return "49805.8" instead of 49805.82.
I have tested on ios and android that have same result.

**Comment by mashiro** [comment]
Its value is a json number, but how did you get a string?
Please show me the minimum code.

**Comment by sandfresh** [comment]
I use rabbit::document to parse string then
  assign the document to rabbit::object.
Then I use str() to get the string of value.
` rabbit::object  object = doc;
  auto playerCreditStr = object["player_credit"].str(); //str() return 49805.8 `

**Comment by mashiro** [comment]
That is the default behavior of std::stringstream.
Instead of using the str method it is better to use boost.lexical_cast and other stringize functions.

https://github.com/mashiro/rabbit/blob/a453e047187da3957d89ab3647442e4501146774/rabbit.hpp#L872
https://wandbox.org/permlink/0RryU6OhPt1G7PJD

**Comment by sandfresh** [comment]
Ok i see . 
Since  I can't use str() to get string directly, I need to know value whether is float or not.
I use as_double to determine whether is float to use as_double or as_int.
json like this {"player_credit","72838.50"}
is_double always return false, is_number as well.

**Comment by mashiro** [comment]
`is_xxx` method is json based type check.
That json value type is string. it's returns true on is_string.
`as_xxx` method is a cast operation, but it is not a conversion operation.
If "player_credit" value is always string, You need parse with any types after call as_string.
