### ISSUE TITLE
Probleme with Operator= for the object and array

### ISSUE THREAD

**Issue by ngaliana** [mashiro/rabbit#6]
Hi,
Very nice your wrapper, more userfriendly that rapidjson. 
I have a problem. When i want to affect an object at another object.
The code with the problem :
`
	 const char* json = "{\"project\":\"rapidjson\",\"stars\":10,\"obj\":{\"input\":\"rapidjson2\",\"output\":100}}";
 doc.parse(json);
rabbit::document doc;
rabbit::object other;
other["other"]="test";
doc["depth"] = other;
std::cout << doc.str() << std::endl;
`
The property "depth" of doc is null.

In your code at line 566/567 you have this : 
  void set(object_tag)                { value_->SetObject(); }
  void set(array_tag)                 { value_->SetArray(); }

Thank you for your reply,

**Comment by mashiro** [comment]
Thank you for reporting.
This is library limitation.
Please use insert instead of assign operator.
```cpp
doc.insert("depth", other);
```

Also updated the library to throw an exception when assigning an object directly.
